### ISSUE TITLE
Запушить на гит

### ISSUE THREAD

**Issue by DeN2828** [DeN2828/FateevTask#2]

**Comment by Timiks1** [comment]
Console.WriteLine("enater date in format DD.MM.YYYY ");
string[] dates = Console.ReadLine().Split('.');
int[] dateNums = new int[3];
dateNums[0] = int.Parse(dates[1]);
dateNums[1] = int.Parse(dates[0]);
dateNums[2] = int.Parse(dates[2]);
int l = 1;
int year = 1995;
if (year < dateNums[2])
{
    for (int i = year; i < dateNums[2]; i++)
    {
        if (l < 20)
        {
            l++;
        }
        else
        {
            l = 1;
        }
    }
}
else
{
    for (int i = year; i > dateNums[2]; i--)
    {
        if (l < 20)
        {
            l++;
        }
        else
        {
            l = 1;
        }
    }
}


int age = dateNums[0] + dateNums[1] + l;
if(age > 30)
{
    age = age - 30;
}
if(age > 0 && age < 7)
{
    Console.WriteLine("rising moon, less than half");
}
else if(age == 7)
{
    Console.WriteLine("rising moon, exactly half");

}
else if(age > 7 && age < 14) {
    Console.WriteLine("rising moon, more than half");

}
else if(age == 14)
{
    Console.WriteLine("full moon");

}
else if (age > 14 && age < 22)
{
    Console.WriteLine("deacrising moon, more than half");

}
else if (age == 22)
{
    Console.WriteLine("deacrising moon, exactly half");

}
else if (age > 22 && age < 29)
{
    Console.WriteLine("deacrising moon, less than half");

}
else if (age > 28)
{
    Console.WriteLine("no moon");
}
